<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Комментарии: Шаббат</title>
	<atom:link href="http://vemo.org.ua/fotogalereya/shabbat/feed" rel="self" type="application/rss+xml" />
	<link>http://vemo.org.ua</link>
	<description>Община новозаветних мессианских верующих в Виннице</description>
	<lastBuildDate>Wed, 01 Jun 2016 21:15:21 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.7.3</generator>
	<item>
		<title>Автор: Оксана</title>
		<link>http://vemo.org.ua/fotogalereya/shabbat/comment-page-1#comment-13468</link>
		<dc:creator><![CDATA[Оксана]]></dc:creator>
		<pubDate>Sun, 01 Mar 2015 22:09:00 +0000</pubDate>
		<guid isPermaLink="false">http://vemo.org.ua/?page_id=7#comment-13468</guid>
		<description><![CDATA[Очень бы хотела с вами пообщаться и узнать, как доносить Благую Весть о Спасителе евреям! Благословений вам!!!]]></description>
		<content:encoded><![CDATA[<p>Очень бы хотела с вами пообщаться и узнать, как доносить Благую Весть о Спасителе евреям! Благословений вам!!!</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.366 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-04-19 00:21:04 -->
