<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Комментарии: Контакты</title>
	<atom:link href="http://vemo.org.ua/kontakty/feed" rel="self" type="application/rss+xml" />
	<link>http://vemo.org.ua</link>
	<description>Община новозаветних мессианских верующих в Виннице</description>
	<lastBuildDate>Wed, 01 Jun 2016 21:15:21 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.7.3</generator>
	<item>
		<title>Автор: николай</title>
		<link>http://vemo.org.ua/kontakty/comment-page-1#comment-15576</link>
		<dc:creator><![CDATA[николай]]></dc:creator>
		<pubDate>Wed, 27 Jan 2016 20:34:35 +0000</pubDate>
		<guid isPermaLink="false">http://vemo.org.ua/?page_id=5#comment-15576</guid>
		<description><![CDATA[сегодня каждый здравомыслящий человек, хотя-бы на миг, вспоминает жертвы холокоста.только память о безневинно убиенных(единственная вина--еврей)может уберечь нас всех:и евреев,и не евреев от подобных ужасных событий.здоровья желаю всем,ВАМ и ВАШИМ  ДЕТЯМ!!!]]></description>
		<content:encoded><![CDATA[<p>сегодня каждый здравомыслящий человек, хотя-бы на миг, вспоминает жертвы холокоста.только память о безневинно убиенных(единственная вина&#8212;еврей)может уберечь нас всех:и евреев,и не евреев от подобных ужасных событий.здоровья желаю всем,ВАМ и ВАШИМ  ДЕТЯМ!!!</p>
]]></content:encoded>
	</item>
	<item>
		<title>Автор: admin</title>
		<link>http://vemo.org.ua/kontakty/comment-page-1#comment-436</link>
		<dc:creator><![CDATA[admin]]></dc:creator>
		<pubDate>Mon, 20 Sep 2010 09:31:42 +0000</pubDate>
		<guid isPermaLink="false">http://vemo.org.ua/?page_id=5#comment-436</guid>
		<description><![CDATA[Шалом :) конечно можно, берите и проигрывайте ;) 
Только, если это конечно возможно - оставьте у себя ссылку на этот общинный сайт ;)]]></description>
		<content:encoded><![CDATA[<p>Шалом :) конечно можно, берите и проигрывайте ;)<br />
Только, если это конечно возможно &#8212; оставьте у себя ссылку на этот общинный сайт ;)</p>
]]></content:encoded>
	</item>
	<item>
		<title>Автор: Алексей</title>
		<link>http://vemo.org.ua/kontakty/comment-page-1#comment-434</link>
		<dc:creator><![CDATA[Алексей]]></dc:creator>
		<pubDate>Sun, 19 Sep 2010 10:08:38 +0000</pubDate>
		<guid isPermaLink="false">http://vemo.org.ua/?page_id=5#comment-434</guid>
		<description><![CDATA[Шалом брати та сестри!
А можно ли нам вашу музыку http://vemo.org.ua/category/muzyka на Первом мессианском радио www.mashiah.info проигрывать?
И если да, то может у вас еще что-то есть. что вы нам можете дать, а мы всем это поставим и они послушают... :)
Поздравляет вас с праздниками и желаем хорошего Суккота!!!
Брахот! Заранее благодарим!

Команда радио &quot;Машиях&quot;]]></description>
		<content:encoded><![CDATA[<p>Шалом брати та сестри!<br />
А можно ли нам вашу музыку <a href="http://vemo.org.ua/category/muzyka" rel="nofollow">http://vemo.org.ua/category/muzyka</a> на Первом мессианском радио <a href="http://www.mashiah.info" rel="nofollow">http://www.mashiah.info</a> проигрывать?<br />
И если да, то может у вас еще что-то есть. что вы нам можете дать, а мы всем это поставим и они послушают&#8230; :)<br />
Поздравляет вас с праздниками и желаем хорошего Суккота!!!<br />
Брахот! Заранее благодарим!</p>
<p>Команда радио &#171;Машиях&#187;</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.276 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-05-14 14:26:00 -->
