<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Комментарии: Фотоотчет о конференции с Сергеем Шидловским в Виннице, день первый</title>
	<atom:link href="http://vemo.org.ua/fotootchet-o-konferencii-s-sergeem-shidlovskim-v-vinnice-den-pervyj.html/feed" rel="self" type="application/rss+xml" />
	<link>http://vemo.org.ua/fotootchet-o-konferencii-s-sergeem-shidlovskim-v-vinnice-den-pervyj.html</link>
	<description>Община новозаветних мессианских верующих в Виннице</description>
	<lastBuildDate>Wed, 01 Jun 2016 21:15:21 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.7.3</generator>
	<item>
		<title>Автор: Аня.. ))</title>
		<link>http://vemo.org.ua/fotootchet-o-konferencii-s-sergeem-shidlovskim-v-vinnice-den-pervyj.html/comment-page-1#comment-99</link>
		<dc:creator><![CDATA[Аня.. ))]]></dc:creator>
		<pubDate>Tue, 25 May 2010 06:43:41 +0000</pubDate>
		<guid isPermaLink="false">http://vemo.org.ua/?p=226#comment-99</guid>
		<description><![CDATA[Красота, красота, КРАСОТИЩА!!!
А Руслан и Женя - ЗВЕЗДЫ!!!!!!! )))))))))))))]]></description>
		<content:encoded><![CDATA[<p>Красота, красота, КРАСОТИЩА!!!<br />
А Руслан и Женя &#8212; ЗВЕЗДЫ!!!!!!! )))))))))))))</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.221 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-04-13 14:54:30 -->
